services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda
      - start
      - --kafka-addr
      - internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr
      - internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr
      - internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr
      - internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr
      - internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr
      - redpanda:9645
      - --advertise-rpc-addr
      - redpanda:9645
      - --smp
      - '1'
      - --memory
      - 1G
      - --mode
      - dev-container
    ports:
      - "19092:19092"
      - "18081:18081"
      - "18082:18082"
      - "9645:9645"
    volumes:
      - redpanda-data:/var/lib/redpanda/data
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      interval: 10s
      timeout: 5s
      retries: 5

  console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
    command:
      - --config
      - /tmp/config.yml
    ports:
      - "8080:8080"
    volumes:
      - ./console-config.yml:/tmp/config.yml
    depends_on:
      redpanda:
        condition: service_healthy

volumes:
  redpanda-data:
